"""add quantity field to production batches

Revision ID: add_quantity_field
Revises: remove_production_fields
Create Date: 2025-09-01 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_quantity_field'
down_revision = 'remove_production_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add quantity column to production_batches table
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove quantity column from production_batches table
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_column('quantity')
    # ### end Alembic commands ###
