"""Generic Alembic revision script."""
from __future__ import annotations
revision = 'd7b149c98edd'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_line_items',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('color', sa.Enum('BLANC', 'BRUN', name='boxcolor'), nullable=True),
    sa.Column('cardboard_type', sa.String(length=64), nullable=True),
    sa.Column('is_cliche', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_line_items_quotation_id'), 'quotation_line_items', ['quotation_id'], unique=False)
    op.create_table('client_order_line_items',
    sa.Column('client_order_id', sa.Integer(), nullable=False),
    sa.Column('quotation_line_item_id', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('color', sa.Enum('BLANC', 'BRUN', name='boxcolor'), nullable=True),
    sa.Column('cardboard_type', sa.String(length=64), nullable=True),
    sa.Column('is_cliche', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_order_id'], ['client_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_item_id'], ['quotation_line_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_order_line_items_client_order_id'), 'client_order_line_items', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_client_order_line_items_quotation_line_item_id'), 'client_order_line_items', ['quotation_line_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_order_line_items_quotation_line_item_id'), table_name='client_order_line_items')
    op.drop_index(op.f('ix_client_order_line_items_client_order_id'), table_name='client_order_line_items')
    op.drop_table('client_order_line_items')
    op.drop_index(op.f('ix_quotation_line_items_quotation_id'), table_name='quotation_line_items')
    op.drop_table('quotation_line_items')
    # ### end Alembic commands ###
