"""remove production fields

Revision ID: remove_production_fields
Revises: e8f3c7d2a1b9
Create Date: 2025-09-01 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'remove_production_fields'
down_revision = 'e8f3c7d2a1b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from production_batches table
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        # Drop indexes first
        batch_op.drop_index('ix_production_batches_stage')
        # Then drop columns
        batch_op.drop_column('stage')
        batch_op.drop_column('produced_quantity')
        batch_op.drop_column('waste_quantity')
        batch_op.drop_column('started_at')
        batch_op.drop_column('completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore columns to production_batches table
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DATETIME(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('waste_quantity', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('produced_quantity', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stage', sa.VARCHAR(), nullable=False, server_default='découpe_impression'))
        # Recreate index
        batch_op.create_index('ix_production_batches_stage', ['stage'])
    # ### end Alembic commands ###
